name: epsp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-55.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
  window_manager: ^0.3.9
  intl:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icons/
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/OpenSans-Medium.ttf